name: Archive & Deploy (all images local)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'  # weekly Monday 06:00 UTC

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run archiver (make ALL images local)
        run: |
          python archive_site.py \
            --base https://ttoka.org \
            --out site \
            --respect-robots \
            --mirror-externals-all \
            --crawl-fallback \
            --max-crawl 1

      - name: Ensure site/index.html exists
        run: |
          if [ ! -f site/index.html ]; then
            if [ -f site/archive-index.html ]; then
              cp site/archive-index.html site/index.html
            else
              echo "<!doctype html><meta charset=utf-8><p>No index yet.</p>" > site/index.html
            fi
          fi

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4